# Generated by Django 4.1.4 on 2023-02-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='body',
        ),
    ]
