# Generated by Django 4.1.4 on 2023-02-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_footerlinkcategory_footerlink_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterEnd',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='category',
        ),
        migrations.DeleteModel(
            name='FooterSocial',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
        migrations.DeleteModel(
            name='FooterLinkCategory',
        ),
    ]
