# Generated by Django 4.2.1 on 2023-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
